#!/usr/bin/env python3
import sys
import re
import urllib
import httplib2
from bs4 import BeautifulSoup


class Poetry(object):
    def __init__(self, title, author, url):
        self.title = title
        self.author = author
        self.url = url


class WebSite():
    HOME = "http://gushi.qinqishuhua.org/"
    SEARCH = HOME + "more.php/?keyWord=%s&type=bt"

    def _get_bs_content(self, url, encoding="gbk"):
        h = httplib2.Http()
        resp, content = h.request(url)
        content = content.decode(encoding, 'ignore')
        doc = BeautifulSoup(content)
        return doc

    def get_poetry_list(self, title, author=None):
        url = self.SEARCH % (urllib.parse.quote(title.encode('gbk')))
        doc = self._get_bs_content(url)

        dirty_result = []
        TITLE = 0
        AUTHOR = 1
        _typ = TITLE
        _title = ""
        _author = ""
        for link in doc.find('ul').find_all('a'):
            if _typ == TITLE:
                _title = link.text
            if _typ == AUTHOR:
                _author = link.text
                dirty_result.append(Poetry(_title, _author, 
                                           url=self.HOME+link.get('href')))
            _typ = not _typ

        clean_result = []
        for poetry in dirty_result:
            if poetry.title != title:
                continue
            if author and (poetry.author != author):
                continue
            clean_result.append(poetry)

        return clean_result

    def get_text(self, poetry):
        url = poetry.url
        doc = self._get_bs_content(url)
        # Encoding/Decoding Error? You need a terminal with fully UTF-8 support, See:
        # http://cncc.bingj.com/cache.aspx?q=UnicodeEncodeError%3a+%27gbk%27+codec+can%27t+encode+character&d=4804969846800574&mkt=zh-CN&setlang=zh-CN&w=i6-M3bdUU_6JDBwk8cLl7x7x1Avd-4L-
        text = str(doc.find(id='contentN').div.div)
        text = text.replace('<br>', '\n')
        text = re.sub('<[^<]+?>', '', text)
        
        result = []
        line_count = 0
        lines = text.splitlines()
        for line in lines:
            line = line.strip()
            if line_count > 2:
                break
            if line == "":
                line_count += 1 
            else:
                result.append(line)
        
        text = "\n".join(result)
        return text


def abort():
    sys.stderr.write("No titie had been given!\n")
    exit(1)

if __name__ == "__main__":
    web = WebSite()
    
    title = None
    author = None

    if len(sys.argv) == 2:
        if sys.argv[1] == "-s":
            title = input("Please enter the title of poetry: ")
        elif not '-' in sys.argv[1]:
            title = sys.argv[1]
        else:
            abort()
    elif len(sys.argv) == 3:
        title = sys.argv[1]
        author = sys.argv[2]
    else:
        abort()

    lst = web.get_poetry_list(title, author)
    if lst:
        for i in lst:
            try:
                print(web.get_text(i))
                break
            except UnicodeEncodeError:
                # cmd.exe doesn't support UTF-8 encoding, try next one
                sys.stderr.write("Error: This terminal doesn't support UTF-8 encoding! Try again...\n")
                continue
    else:
        sys.stderr.write("%s: No such poetry\n" % title)
